Repository oz-collabo-project-team-03/oz-project-03-fe, pull requests merged in 2024-11, with the labels that each got.

#3 Design/공통 컴포넌트 스타일링
  public/fonts/GmarketSansBold.otf
  src/App.tsx
  src/assets/assets.ts
  src/assets/header/back.svg
  src/assets/header/chat.svg
  src/assets/navBar/chat_active.svg
  src/assets/navBar/chat_outline.svg
  src/assets/navBar/home_active.svg
  src/assets/navBar/home_outline.svg
  src/assets/navBar/student/plus_active.svg
  src/assets/navBar/student/plus_outline_.svg
  src/assets/navBar/teacher/user_Active.svg
  src/assets/navBar/teacher/user_outline.svg
  src/components/Component
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/StudentNavBar.tsx
  src/components/common/TeacherNavBar.tsx
  src/components/common/ToastMessage.tsx
  src/context/ToastContextProvider.tsx
  src/index.css
  src/layouts/defaultLayout.tsx
  tailwind.config.js
Labels: 우선순위: 🟡 중간, 🎨 Design

#6 Design/로그인 페이지 스타일 작업
  src/App.tsx
  src/assets/assets.ts
  src/assets/login/google_login.svg
  src/assets/login/kakao_logo.png
  src/assets/login/naver_logo.svg
  src/components/common/Input.tsx
  src/context/ToastContextProvider.tsx
  src/index.css
  src/layouts/defaultLayout.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/auth/loginPage.tsx
  src/router/index.tsx
Labels: 우선순위: 🟢 낮음, 🎨 Design

#11 Design/회원가입 스타일 작업
  package.json
  src/assets/assets.ts
  src/assets/auth/google_login.svg
  src/assets/auth/kakao_logo.png
  src/assets/auth/naver_logo.svg
  src/assets/auth/thumbs_up.svg
  src/assets/roleSelect/role_student_active.svg
  src/assets/roleSelect/role_student_unactive.svg
  src/assets/roleSelect/role_teacher_active.svg
  src/assets/roleSelect/role_teacher_unactive.svg
  src/components/auth/GradeButton.tsx
  src/components/common/AuthInput.tsx
  src/components/common/ConfettiCelebration.tsx
  src/components/common/Header.tsx
  src/components/common/ToastMessage.tsx
  src/components/terms/Terms.tsx
  src/hooks/useHook
  src/hooks/useValidateAndProceed.ts
  src/index.css
  src/layouts/defaultLayout.tsx
  src/mocks/termsData.ts
  src/pages/auth/loginPage.tsx
  src/pages/auth/roleSelectPage.tsx
  src/pages/auth/signupCompletePage.tsx
  src/pages/auth/signupPage.tsx
  src/pages/auth/termsOfServicePage.tsx
  src/pages/pages
  src/router/index.tsx
  yarn.lock
Labels: 우선순위: 🟡 중간, 🎨 Design

#13 Design/학생,교사 공통 Layout 제작
  src/index.css
  src/layouts/studentLayout.tsx
  src/layouts/teacherLayout.tsx
  src/router/index.tsx
  tailwind.config.js
Labels: 우선순위: 🟢 낮음, 🎨 Design

#15 Design/프로필 수정 페이지 스타일
  src/components/editProfile/ProfileImages.tsx
  src/pages/editProfile/editProfile.tsx
  src/pages/myPage/myPage.tsx
  src/router/index.tsx
Labels: 우선순위: 🟡 중간, 🎨 Design

#19 Design/회원정보 변경 페이지 스타일 작업
  src/components/changeProfile/EditAccount.tsx
  src/components/changeProfile/PwCheck.tsx
  src/pages/changeProfile/changeProfile.tsx
  src/router/index.tsx
Labels: 우선순위: 🟡 중간, 🎨 Design

#20 Refactor/로그인,회원가입관련 코드 리팩토링
  public/fonts/GmarketSansBold.otf
  src/App.css
  src/components/auth/AuthInput.tsx
  src/components/common/Button.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/ToastMessage.tsx
  src/components/terms/ShowPrivacyTerms.tsx
  src/components/terms/ShowThirdPartyTerms.tsx
  src/components/terms/Terms.tsx
  src/index.css
  src/mocks/termsData.ts
  src/pages/auth/roleSelectPage.tsx
  src/pages/auth/signupPage.tsx
  src/pages/auth/termsOfServicePage.tsx
  src/pages/editProfile/editProfile.tsx
  src/pages/loadingPage.tsx
  src/router/index.tsx
Labels: 우선순위: 🟢 낮음, ♻️ Refactor, 🎨 Design, 🩹Chore, 🚚 Rename, 🔥 Remove

#23 rename/선생,학생 네브바 경로이동
  src/components/auth/AuthInput.tsx
  src/components/navigatorBar/StudentNavBar.tsx
  src/components/navigatorBar/TeacherNavBar.tsx
  src/layouts/studentLayout.tsx
  src/layouts/teacherLayout.tsx
Labels: 우선순위: 🔴 긴급, 🚚 Rename

#27 Refactor/메인 랜딩 페이지 리팩토링 작업
  src/components/landing/BouncingBalls.tsx
Labels: 우선순위: 🔴 긴급, ♻️ Refactor

#29 Refactor/프로필 변경 페이지 연결 및 AuthInput 경로 변경
  src/components/changeProfile/EditAccount.tsx
  src/router/index.tsx
Labels: 우선순위: 🔴 긴급, ♻️ Refactor

#30 Design/메인 피드 페이지 스타일 작업
  src/assets/feedPost/chat.svg
  src/assets/feedPost/fullHeart.svg
  src/assets/feedPost/heart.svg
  src/components/common/MainHeader.tsx
  src/components/main/FeedPost.tsx
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostSlider.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/pages/main/homeFeedPage.tsx
  src/pages/main/managedStudentListPage.tsx
  src/router/index.tsx
Labels: 우선순위: 🟡 중간, 🎨 Design, 🩹Chore

#31 Design/메인 피드 페이지 스타일 작업
  src/components/main/FeedPost.tsx
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostSlider.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/pages/main/homeFeedPage.tsx
  src/stores/useFeedPostStore.ts
  tailwind.config.js
Labels: 우선순위: 🟡 중간, 🎨 Design, 🍱 Add

#33 [Design] Chat List page 및 Chatting Room page
  src/assets/assets.ts
  src/assets/chat/chat_delete.svg
  src/assets/modal/modal_close.svg
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatItem.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/HelpButton.tsx
  src/components/chat/bubbles/ChatAiBubble.tsx
  src/components/chat/bubbles/ChatMyBubble.tsx
  src/components/chat/bubbles/ChatTeacherBubble.tsx
  src/components/common/Header.tsx
  src/components/modal/CreateChatModal.tsx
  src/components/modal/DeleteChatModal.tsx
  src/pages/chat/studentChatListPage.tsx
  src/pages/chat/studentChatRoomPage.tsx
  src/pages/chat/teacherChatListPage.tsx
  src/router/index.tsx
  src/types/chat.ts
  src/types/index.ts
  tailwind.config.js
Labels: 우선순위: 🟡 중간, 🎨 Design, 🍱 Add, 🩹Chore

#34 Design/메인 피드 페이지 스타일 작업
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/pages/main/homeFeedPage.tsx
  src/stores/useFeedPostStore.ts
Labels: 우선순위: 🟠 높음, 🎨 Design

#36 feat/회원가입mockAPI 생성
  package.json
  src/api/auth/sendcode.hooks.ts
  src/api/auth/signup.hooks.ts
  src/components/ConfettiCelebration.tsx
  src/components/auth/AuthInput.tsx
  src/components/auth/GradeButton.tsx
  src/context/ToastContextProvider.tsx
  src/hooks/useCountDown.ts
  src/hooks/useToast.ts
  src/hooks/useValidateAndProceed.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/auth/roleSelectPage.tsx
  src/pages/auth/signupCompletePage.tsx
  src/pages/auth/signupPage.tsx
  src/pages/auth/termsOfServicePage.tsx
  src/stores/useTermsStore.tsx
  src/types/emailType.ts
  src/types/signupType.ts
  src/types/type
  tsconfig.json
  yarn.lock
Labels: 우선순위: 🟡 중간, ✨Feature

#40 Design/선생님 마이 페이지
  src/components/changeProfile/EditAccount.tsx
  src/components/myPage/StudentPage.tsx
  src/components/myPage/TeacherPage.tsx
  src/pages/myPage/myPage.tsx
Labels: 우선순위: 🟢 낮음, 🎨 Design

#43 Feat/로그인 mockAPI 연결
  src/api/auth/login.hooks.ts
  src/components/common/Input.tsx
  src/mocks/handlers.ts
  src/pages/auth/loginPage.tsx
  src/pages/auth/signupPage.tsx
  src/types/apiErrorType.ts
  src/types/loginType.ts
Labels: 우선순위: 🟠 높음, ✨Feature

#45 [Refactor] chat refactor
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatItem.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/HelpButton.tsx
  src/components/chat/bubbles/ChatAiBubble.tsx
  src/components/chat/bubbles/ChatMyBubble.tsx
  src/components/chat/bubbles/ChatTeacherBubble.tsx
  src/components/modal/CreateChatModal.tsx
  src/components/modal/DeleteChatModal.tsx
Labels: 우선순위: 🟢 낮음, ♻️ Refactor, 🎨 Design

#47 chore: 절대경로 지정
  package-lock.json
  package.json
  public/mockServiceWorker.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 우선순위: 🟢 낮음, ⚙️ conf, 🩹Chore

#55 Design, Feat/선생님 마이페이지, mock api 연결
  src/api/editProfile/editProfile.hooks.ts
  src/components/auth/AuthInput.tsx
  src/components/common/Header.tsx
  src/components/editProfile/ProfileImages.tsx
  src/components/editProfile/inputFields/CommonFields.tsx
  src/components/editProfile/inputFields/StudentProfileFields.tsx
  src/components/editProfile/inputFields/TeacherProfileFields.tsx
  src/components/myPage/StudentPage.tsx
  src/components/myPage/TeacherPage.tsx
  src/mocks/browser.ts
  src/mocks/editProfileHandlers.ts
  src/mocks/myPageHandlers.ts
  src/pages/editProfile/editProfile.tsx
  src/pages/myPage/myPage.tsx
  src/stores/editProfile/useProfileStore.ts
  src/types/editProfile.ts
  src/types/myPageType.ts
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, ✨Feature, 🩹Chore

#60 Design/마이페이지 설정 버튼 스타일 작업
  src/assets/assets.ts
  src/assets/myPage/editIcon.svg
  src/assets/myPage/logoutIcon.svg
  src/assets/myPage/toggleIcon.svg
  src/components/myPage/StudentPage.tsx
  src/components/myPage/TeacherPage.tsx
  src/components/myPage/ToggleButton.tsx
  tailwind.config.js
Labels: 우선순위: 🟡 중간, 🎨 Design, 🍱 Add

#62 Refactor/마이페이지 컴포넌트 리팩토링
  src/api/editProfile/editProfile.hooks.ts
  src/api/editProfile/editProfileAPI.ts
  src/api/myPage/myPage.hooks.ts
  src/api/myPage/myPageAPI.ts
  src/components/editProfile/ProfileImages.tsx
  src/components/editProfile/inputFields/CommonFields.tsx
  src/components/editProfile/inputFields/StudentProfileFields.tsx
  src/components/editProfile/inputFields/TeacherProfileFields.tsx
  src/components/landing/SubLanding.tsx
  src/components/myPage/CommunityInfo.tsx
  src/components/myPage/PostGrid.tsx
  src/components/myPage/ProfileHeader.tsx
  src/components/myPage/StudentPage.tsx
  src/components/myPage/TeacherPage.tsx
  src/mocks/editProfileHandlers.ts
  src/mocks/myPageHandlers.ts
  src/pages/editProfile/editProfile.tsx
  src/pages/landing/landing.tsx
  src/pages/myPage/myPage.tsx
  src/stores/editProfile/useProfileStore.ts
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🔥 Remove

#65 Feat/axiosinstance 동적설정
  package.json
  src/api/auth/login/loginAPI.ts
  src/api/auth/sendEmail/sendEmailAPI.ts
  src/api/auth/signup/signup.hooks.ts
  src/api/auth/signup/signupAPI.ts
  src/api/axiosInstance.ts
  src/api/request
  src/context/ToastContextProvider.tsx
  src/hooks/useToast.ts
  src/pages/auth/loginPage.tsx
  src/pages/auth/roleSelectPage.tsx
  src/pages/auth/signupCompletePage.tsx
  src/pages/auth/signupPage.tsx
  src/pages/auth/termsOfServicePage.tsx
  yarn.lock
Labels: 우선순위: 🟡 중간, ✨Feature

#67 Feat/ 대글 모달 스타일 작업
  src/assets/posting/deleteIcon.svg
  src/assets/posting/photo.svg
  src/components/comment/Comment.tsx
  src/components/comment/CommentHeader.tsx
  src/components/comment/Reply.tsx
  src/components/main/MainHeader.tsx
  src/components/main/ManagedList.tsx
  src/components/modal/CommentModal.tsx
  src/components/posting/PostImageUpload.tsx
  src/components/posting/PostTextEditor.tsx
  src/pages/main/homeFeedPage.tsx
  src/pages/posting/createPostPage.tsx
  tailwind.config.js
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, ✨Feature

#68 Feat/마이 페이지 게시글 mock api 연결
  src/api/myPage/myPage.hooks.ts
  src/api/myPage/myPageAPI.ts
  src/api/postDetail/postDetail.hooks.ts
  src/api/postDetail/postDetailAPI.ts
  src/assets/assets.ts
  src/components/editProfile/ProfileImages.tsx
  src/components/myPage/PostGrid.tsx
  src/components/myPage/ProfileHeader.tsx
  src/hooks/useGestureControl.ts
  src/hooks/useProfileImages.ts
  src/mocks/browser.ts
  src/mocks/myPageHandlers.ts
  src/mocks/postDetailHandlers.ts
  src/pages/editProfile/editProfile.tsx
  src/pages/myPage/myPage.tsx
  src/pages/postDetail/postDetail.tsx
  src/router/index.tsx
  src/types/myPageType.ts
  src/types/postDetail.ts
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, ✨Feature

#69 Refactor/로그인,회원가입 관련 리팩토링
  package.json
  src/App.tsx
  src/api/auth/sendEmail/sendEmailAPI.ts
  src/api/auth/signup/signupAPI.ts
  src/assets/assets.ts
  src/assets/error/error.svg
  src/assets/notfound/notfound.svg
  src/components/terms/ShowPrivacyTerms.tsx
  src/components/terms/ShowThirdPartyTerms.tsx
  src/hooks/signup/useCountDown.ts
  src/hooks/signup/useEmailVerification.ts
  src/hooks/signup/useSignupForm.ts
  src/layouts/defaultLayout.tsx
  src/layouts/studentLayout.tsx
  src/layouts/teacherLayout.tsx
  src/pages/auth/findPasswordPage.tsx
  src/pages/auth/roleSelectPage.tsx
  src/pages/auth/signupPage.tsx
  src/pages/auth/termsOfServicePage.tsx
  src/pages/status/errorPage.tsx
  src/pages/status/loadingPage.tsx
  src/pages/status/notfoundPage.tsx
  src/router/index.tsx
  src/schemas/signupValidationSchemas.ts
  src/stores/useTermsStore.ts
  src/stores/useTermsStore.tsx
  src/types/signupType.ts
  yarn.lock
Labels: 우선순위: 🟢 낮음, ♻️ Refactor, 🎨 Design, 🍱 Add

#76 Refactor/댓글 모달 기능 개선, 스타일 수정 및 상태 관리 추가
  src/assets/comment/send.svg
  src/components/comment/Comment.tsx
  src/components/comment/CommentHeader.tsx
  src/components/main/FeedPostButton.tsx
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostSlider.tsx
  src/components/modal/CommentModal.tsx
  src/index.css
  src/pages/main/homeFeedPage.tsx
  src/stores/useCommentModalStore.tsx
  src/stores/useFeedPostStore.ts
  src/styles/sliderSlick.css
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, ✨Feature, 🍱 Add, 🚚 Rename

#77 Refactor/mockAPI 백엔드 API로 바꾸는 작업
  src/api/auth/login/loginAPI.ts
  src/api/auth/login/loginType.ts
  src/api/auth/sendEmail/sendEmailAPI.ts
  src/api/auth/signup/signupAPI.ts
  src/pages/auth/loginPage.tsx
Labels: 우선순위: 🟡 중간, ♻️ Refactor

#78 Refactor/랜딩페이지 접근성 수정
  src/assets/assets.ts
  src/assets/landing/bottomArrow.svg
  src/assets/landing/iphone.svg
  src/components/landing/SubLanding.tsx
Labels: 우선순위: 🟢 낮음, ♻️ Refactor, 🎨 Design, 🍱 Add

#81 Fix/학생,선생님 메인페이지 & 모달 ui 및 오류 수정
  src/components/comment/Comment.tsx
  src/components/main/FeedPostSlider.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/components/main/ManagedList.tsx
  src/components/main/TeacherInfo.tsx
  src/components/modal/CommentModal.tsx
  src/pages/main/homeFeedPage.tsx
  src/pages/main/managedStudentListPage.tsx
  src/styles/sliderSlick.css
Labels: 우선순위: 🟡 중간, 🎨 Design, 🐛Bug

#84 Refactor/비밀번호 유효성검사 수정 및 백엔드API 전환 작업
  src/api/auth/findEmail/findEmail.hooks.ts
  src/api/auth/findEmail/findEmailAPI.ts
  src/api/auth/login/login.hooks.ts
  src/api/auth/login/loginType.ts
  src/api/auth/logout/logout.hooks.ts
  src/api/auth/logout/logoutAPI.ts
  src/api/auth/logout/logoutType.ts
  src/api/auth/resetPassword/resetPassword.hooks.ts
  src/api/auth/resetPassword/resetPasswordAPI.ts
  src/api/auth/resetPassword/resetPasswordType.ts
  src/api/auth/sendEmail/sendEmail.hooks.ts
  src/api/auth/signup/signup.hooks.ts
  src/api/axiosInstance.ts
  src/components/auth/AuthInput.tsx
  src/components/myPage/ToggleButton.tsx
  src/components/terms/ShowPrivacyTerms.tsx
  src/components/terms/ShowThirdPartyTerms.tsx
  src/hooks/findEmail/useFindEmail.ts
  src/hooks/login/useLogin.ts
  src/hooks/logout/useLogout.ts
  src/hooks/resetPassword/useResetPassword.ts
  src/hooks/signup/useEmailVerification.ts
  src/hooks/signup/useSignupForm.ts
  src/pages/auth/findEmailPage.tsx
  src/pages/auth/loginPage.tsx
  src/pages/auth/resetPasswordPage.tsx
  src/pages/auth/signupPage.tsx
  src/schemas/signupValidationSchemas.ts
Labels: 우선순위: 🟡 중간, ♻️ Refactor

#91 Style/전체적으로 코드 포맷팅
  .eslintrc.cjs
  eslint.config.js
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/authHandlers.ts
  src/pages/chat/teacherChatListPage.tsx
  src/pages/editProfile/editProfile.tsx
  src/pages/landing/landing.tsx
  src/pages/main/homeFeedPage.tsx
  src/pages/myPage/myPage.tsx
  src/types/chat.ts
  src/types/index.ts
Labels: 우선순위: 🟢 낮음, 💄style

#93 Feat/선생님 조회,선택 mockAPI 생성 및 최초로그인시 모달 띄우기
  src/api/auth/login/loginType.ts
  src/api/auth/resetPassword/resetPasswordAPI.ts
  src/api/teacher/teacher.hooks.ts
  src/api/teacher/teacherAPI.ts
  src/api/teacher/teacherQueries.ts
  src/components/common/Button.tsx
  src/components/modal/TeacherListModal.tsx
  src/hooks/login/useLogin.ts
  src/hooks/selectedTeacher/useSelectedTeacher.ts
  src/mocks/browser.ts
  src/mocks/teachersAndGroupsHandlers.ts
  src/pages/main/homeFeedPage.tsx
  src/types/teacherType.ts
Labels: 우선순위: 🟡 중간, ✨Feature
