Repository oz-collabo-project-team-03/oz-project-03-fe, pull requests merged in 2024-12, with the labels that each got.

#97 Refactor/mockAPI 핸들러 수정, 리액트 쿼리 사용법 통일
  src/api/editProfile/editProfileAPI.ts
  src/components/changeProfile/VerifyPassword.tsx
  src/components/main/FeedPost.tsx
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/mocks/editProfileHandlers.ts
  src/mocks/homeFeedHandlers.ts
  src/mocks/myPageHandlers.ts
  src/mocks/postDetailHandlers.ts
  src/mocks/verifyPasswordHandlers.ts
  src/pages/editProfile/editProfile.tsx
  src/pages/main/homeFeedPage.tsx
  src/schemas/editProfileSchemas.ts
  src/types/postType.ts
Labels: 우선순위: 🟢 낮음, ♻️ Refactor, ✨Feature, 💄style

#98 Refactor/인터셉터 상태코드 추가
  src/api/axiosInstance.ts
  src/api/teacher/teacherAPI.ts
  src/api/teacher/teacherQueries.ts
  src/components/modal/TeacherListModal.tsx
  src/hooks/findEmail/useFindEmail.ts
  src/hooks/login/useLogin.ts
  src/hooks/selectedTeacher/useSelectedTeacher.ts
  src/hooks/signup/useEmailVerification.ts
  src/hooks/signup/useSignupForm.ts
  src/types/teacherType.ts
Labels: 우선순위: 🟢 낮음, ♻️ Refactor

#100 Feature/포스팅 페이지 API생성 및 연결
  src/api/comment/fetchComment/fetchComment.hooks.ts
  src/api/comment/fetchComment/fetchCommentAPI.ts
  src/api/comment/fetchComment/fetchCommentType.ts
  src/api/createPosting/createPosting.hooks.ts
  src/api/createPosting/createPostingAPI.ts
  src/components/modal/PostingModal.tsx
  src/components/posting/PostImageUpload.tsx
  src/components/posting/PostTextEditor.tsx
  src/pages/posting/createPostPage.tsx
  src/stores/useCommentModalStore.ts
  src/types/createPostingType.ts
Labels: 우선순위: 🟡 중간, ✨Feature

#101 Refactor/createPostPage API 연결로직 수정
  src/api/createPosting/createPostingAPI.ts
  src/components/main/FeedPostContent.tsx
  src/components/posting/PostImageUpload.tsx
  src/pages/posting/createPostPage.tsx
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🐛Bug

#102 Feat/Chat List API 연결
  package.json
  src/api/chat/chatList/chatList.hooks.ts
  src/api/chat/chatList/chatListAPI.ts
  src/api/chat/chatList/chatListType.ts
  src/api/chat/createChatRoom/createChatRoom.hooks.ts
  src/api/chat/createChatRoom/createChatRoomAPI.ts
  src/api/chat/createChatRoom/createChatRoomType.ts
  src/api/chat/deleteChatRoom/deleteChatRoom.hooks.ts
  src/api/chat/deleteChatRoom/deleteChatRoomAPI.ts
  src/api/chat/deleteChatRoom/deleteChatRoomType.ts
  src/components/chat/ChatItem.tsx
  src/components/modal/CreateChatModal.tsx
  src/index.css
  src/pages/chat/studentChatListPage.tsx
  yarn.lock
Labels: 우선순위: 🟡 중간, 🎨 Design, ✨Feature, 🐛Bug, 🩹Chore

#105 Feat/Chat help list api
  src/api/chat/chatHelpList/chatHelpList.hooks.ts
  src/api/chat/chatHelpList/chatHelpListAPI.ts
  src/api/chat/chatHelpList/chatHelpListType.ts
  src/index.css
  src/pages/chat/studentChatListPage.tsx
  src/pages/chat/teacherChatListPage.tsx
Labels: 우선순위: 🟡 중간, 🎨 Design, ✨Feature

#107 Feat/회원정보 변경 api 생성 및 연결 2차
  src/api/auth/changeProfile/editAccount/editAccount.hooks.ts
  src/api/auth/changeProfile/editAccount/editAccountAPI.ts
  src/api/auth/changeProfile/editAccount/editAccountType.ts
  src/components/changeProfile/EditAccount.tsx
  src/components/changeProfile/VerifyPassword.tsx
  src/hooks/changeProfile/useEditAccountForm.ts
  src/hooks/changeProfile/useVerifyPasswordForm.ts
  src/pages/changeProfile/changeProfile.tsx
  src/pages/main/homeFeedPage.tsx
  src/schemas/editAccountSchemas.ts
Labels: 우선순위: 🟡 중간, ♻️ Refactor, ✨Feature, 🐛Bug, 🔥 Remove

#111 Deploy/임시 배포를 위한 빌드
  src/components/modal/PostingModal.tsx
  src/components/navigatorBar/BaseNavBar.tsx
  src/components/navigatorBar/StudentNavBar.tsx
  src/components/navigatorBar/TeacherNavBar.tsx
  src/hooks/useLayoutNavIcon.ts
  src/mocks/teachersAndGroupsHandlers.ts
Labels: 🚀 Deploy, 우선순위: 🟡 중간, 🐛Bug

#112 Feature/댓글 모달 API생성 및 연결
  src/api/comment/deleteComment/deleteComment.hooks.ts
  src/api/comment/deleteComment/deleteCommentAPI.ts
  src/api/comment/deleteComment/deleteCommentType.ts
  src/api/comment/fetchComment/fetchComment.hooks.ts
  src/api/comment/fetchComment/fetchCommentAPI.ts
  src/api/comment/fetchComment/fetchCommentType.ts
  src/api/comment/writeComment/writeComment.hooks.ts
  src/api/comment/writeComment/writeCommentAPI.ts
  src/api/comment/writeComment/writeCommentType.ts
  src/components/comment/Comment.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/Reply.tsx
  src/components/modal/CommentModal.tsx
Labels: 우선순위: 🟡 중간, ✨Feature, 🚚 Rename, 🔥 Remove

#113 Feat/Chatting API 연결
  src/api/chat/chatHelp/chatHelp.hooks.ts
  src/api/chat/chatHelp/chatHelpAPI.ts
  src/api/chat/chatHelp/chatHelpType.ts
  src/api/chat/chatMessages/chatMessages.hooks.ts
  src/api/chat/chatMessages/chatMessagesAPI.ts
  src/api/chat/chatMessages/chatMessagesType.ts
  src/api/chat/createChatRoom/createChatRoom.hooks.ts
  src/api/chat/createChatRoom/createChatRoomAPI.ts
  src/api/chat/createChatRoom/createChatRoomType.ts
  src/assets/assets.ts
  src/assets/chat/chat_preview.svg
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/bubbles/ChatAiBubble.tsx
  src/components/chat/bubbles/ChatMyBubble.tsx
  src/components/chat/bubbles/ChatOtherBubble.tsx
  src/components/chat/bubbles/ChatSystemBubble.tsx
  src/components/chat/bubbles/ChatTeacherBubble.tsx
  src/components/chat/bubbles/index.ts
  src/components/modal/CreateChatModal.tsx
  src/components/modal/PreviewImageModal.tsx
  src/pages/chat/studentChatListPage.tsx
  src/pages/chat/studentChatRoomPage.tsx
  src/pages/chat/teacherChatRoomPage.tsx
  src/types/chat.ts
Labels: 우선순위: 🟡 중간, ✨Feature, 🐛Bug, 🍱 Add, 🩹Chore

#117 Refactor/코드 통일화
  src/api/auth/findEmail/findEmail.hooks.ts
  src/api/auth/findEmail/findEmailAPI.ts
  src/api/auth/findEmail/findEmailType.ts
  src/api/auth/login/login.hooks.ts
  src/api/auth/login/loginAPI.ts
  src/api/auth/login/loginType.ts
  src/api/auth/logout/logout.hooks.ts
  src/api/auth/resetPassword/resetPassword.hooks.ts
  src/api/auth/resetPassword/resetPasswordAPI.ts
  src/api/auth/resetPassword/resetPasswordType.ts
  src/api/auth/sendEmail/emailType.ts
  src/api/auth/sendEmail/sendEmail.hooks.ts
  src/api/auth/sendEmail/sendEmailAPI.ts
  src/api/auth/signup/signup.hooks.ts
  src/api/teacher/teacher.hooks.ts
  src/api/teacher/teacherAPI.ts
  src/components/modal/TeacherListModal.tsx
  src/components/terms/ShowPrivacyTerms.tsx
  src/components/terms/ShowThirdPartyTerms.tsx
  src/hooks/findEmail/useFindEmail.ts
  src/hooks/login/useLogin.ts
  src/hooks/logout/useLogout.ts
  src/hooks/resetPassword/useResetPassword.ts
  src/hooks/signup/useEmailVerification.ts
  src/hooks/signup/useSignupForm.ts
  src/hooks/teacherSelection/useTeacherSelection.ts
  src/pages/auth/findEmailPage.tsx
  src/pages/auth/resetPasswordPage.tsx
  src/pages/auth/roleSelectPage.tsx
  src/pages/auth/signupCompletePage.tsx
  src/pages/auth/signupPage.tsx
  src/pages/auth/termsOfServicePage.tsx
  src/stores/useTermsStore.ts
  src/types/signupType.ts
  src/types/teacherType.ts
Labels: 우선순위: 🟡 중간, ♻️ Refactor

#122 Feat/탈퇴 api 연결
  src/api/auth/cancleMember/cancelAPI.ts
  src/api/auth/cancleMember/cancelMember.hooks.ts
  src/api/auth/cancleMember/cancelType.ts
  src/components/changeProfile/EditAccount.tsx
  src/components/common/Button.tsx
  src/components/modal/CancelMemberModal.tsx
  src/components/modal/PostingModal.tsx
  src/pages/posting/createPostPage.tsx
  tailwind.config.js
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, ✨Feature

#126 Refactor/api 연결 오류 해결
  src/api/auth/changeProfile/editAccount/editAccount.hooks.ts
  src/api/auth/changeProfile/verifyPassword/verifyPassword.hooks.ts
  src/api/auth/signup/signup.hooks.ts
  src/api/editProfile/editProfile.hooks.ts
  src/api/homeFeed/homeFeed.hooks.ts
  src/api/myPage/myPage.hooks.ts
  src/api/postDetail/postDetail.hooks.ts
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostSlider.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/components/main/TeacherInfo.tsx
  src/components/myPage/PostGrid.tsx
  src/components/myPage/ProfileHeader.tsx
  src/hooks/changeProfile/useEditAccountForm.ts
  src/hooks/resetPassword/useResetPassword.ts
  src/mocks/teachersAndGroupsHandlers.ts
  src/pages/editProfile/editProfile.tsx
  src/pages/myPage/myPage.tsx
  src/pages/postDetail/postDetail.tsx
  src/styles/sliderSlick.css
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, 🐛Bug, 🔥 Remove

#128 Refactor, Design/백엔드와 소통하여 요청 & 응답 값 수정, 커스텀 스크롤 적용
  src/api/editProfile/editProfileAPI.ts
  src/assets/editProfile/student/studentIcon1.png
  src/assets/editProfile/teacher/teacherIcon1.png
  src/components/editProfile/ProfileImages.tsx
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/components/main/TeacherInfo.tsx
  src/components/myPage/ProfileHeader.tsx
  src/components/navigatorBar/StudentNavBar.tsx
  src/components/navigatorBar/TeacherNavBar.tsx
  src/hooks/getProfileImages.ts
  src/mocks/homeFeedHandlers.ts
  src/mocks/myPageHandlers.ts
  src/mocks/postDetailHandlers.ts
  src/pages/myPage/myPage.tsx
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, 🐛Bug, 🚚 Rename

#130 Refactor/설정 버튼 이벤트 변경
  src/components/myPage/ToggleButton.tsx
Labels: 우선순위: 🟢 낮음, ♻️ Refactor

#132 Refactor/프로필 일부 정보만 변경 가능하도록 로직 수정
  src/api/editProfile/editProfile.hooks.ts
  src/api/editProfile/editProfileAPI.ts
  src/pages/editProfile/editProfile.tsx
  src/schemas/editProfileSchemas.ts
  src/types/editProfileType.ts
Labels: 우선순위: 🟢 낮음, ♻️ Refactor, 🐛Bug, 🚚 Rename, 🔥 Remove

#136 Feat/대댓글 & 관리하는 학생 리스트 API연결 외
  src/api/auth/signup/signup.hooks.ts
  src/api/auth/signup/signupAPI.ts
  src/api/comment/fetchComment/fetchComment.hooks.ts
  src/api/comment/fetchComment/fetchCommentAPI.ts
  src/api/comment/fetchComment/fetchCommentType.ts
  src/api/comment/writeComment/writeComment.hooks.ts
  src/api/comment/writeComment/writeCommentAPI.ts
  src/api/comment/writeComment/writeCommentType.ts
  src/api/studentsList/studentsList.hook.ts
  src/api/studentsList/studentsListAPI.ts
  src/api/studentsList/studentsListType.ts
  src/components/comment/CommentList.tsx
  src/components/comment/CommentProfileImage.tsx
  src/components/comment/ReComment.tsx
  src/components/main/FeedPost.tsx
  src/components/main/FeedPostButton.tsx
  src/components/main/FeedPostContent.tsx
  src/components/main/ManagedList.tsx
  src/components/main/TeacherInfo.tsx
  src/components/modal/CommentModal.tsx
  src/components/navigatorBar/TeacherNavBar.tsx
  src/hooks/login/useLogin.ts
  src/pages/auth/loginPage.tsx
  src/pages/main/homeFeedPage.tsx
  src/pages/main/managedStudentListPage.tsx
  src/router/index.tsx
  src/stores/useCommentModalStore.ts
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, ✨Feature, 🐛Bug, 🩹Chore

#140 Refactor/api 연결 오류 해결, 디테일 기능 작업
  src/api/myPage/myPage.hooks.ts
  src/api/postDetail/postDetail.hooks.ts
  src/api/postDetail/postDetailAPI.ts
  src/components/changeProfile/EditAccount.tsx
  src/components/editProfile/ProfileImages.tsx
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostSlider.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/components/myPage/CommunityInfo.tsx
  src/components/myPage/PostGrid.tsx
  src/components/navigatorBar/BaseNavBar.tsx
  src/components/navigatorBar/StudentNavBar.tsx
  src/components/navigatorBar/TeacherNavBar.tsx
  src/hooks/logout/useLogout.ts
  src/hooks/useScrollPosition.ts
  src/layouts/studentLayout.tsx
  src/layouts/teacherLayout.tsx
  src/pages/editProfile/editProfile.tsx
  src/pages/main/homeFeedPage.tsx
  src/pages/myPage/myPage.tsx
  src/pages/postDetail/postDetail.tsx
  src/stores/editProfile/useProfileStore.ts
  src/styles/sliderSlick.css
  src/types/postType.ts
Labels: 우선순위: 🟢 낮음, 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, ✨Feature, 🐛Bug, 🔥 Remove

#143 Fix/홈 피드 페이지에서 협업 선생님 클릭 시 네브바 오류
  src/components/comment/CommentProfileImage.tsx
  src/components/editProfile/inputFields/TeacherProfileFields.tsx
  src/components/main/FeedPostButton.tsx
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/components/main/ManagedList.tsx
  src/components/main/TeacherInfo.tsx
  src/components/modal/CommentModal.tsx
  src/components/navigatorBar/TeacherNavBar.tsx
  src/context/UserInfoContextProvider.tsx
  src/hooks/signup/useUpdateSocialInfo.ts
  src/layouts/studentLayout.tsx
  src/layouts/teacherLayout.tsx
  src/main.tsx
  src/pages/myPage/myPage.tsx
  src/pages/postDetail/postDetail.tsx
  src/router/index.tsx
  src/types/editProfileType.ts
  src/types/myPageType.ts
  tsconfig.json
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 📃 Docs, 🐛Bug

#144 Refactor/소셜로그인 선생님 추가정보입력
  src/api/myPage/myPage.hooks.ts
  src/api/social/social.hooks.ts
  src/api/social/socialAPI.ts
  src/api/social/socialType.ts
  src/api/teacher/teacherAPI.ts
  src/context/AuthContextProvider.tsx
  src/hooks/login/useLogin.ts
  src/hooks/signup/useSignupForm.ts
  src/hooks/signup/useUpdateSocialInfo.ts
  src/hooks/useAuth.ts
  src/index.css
  src/pages/auth/loginHandlerPage.tsx
  src/pages/auth/roleSelectPage.tsx
  src/pages/auth/signupCompletePage.tsx
  src/pages/auth/signupPage.tsx
  src/pages/auth/termsOfServicePage.tsx
  src/pages/main/homeFeedPage.tsx
  src/router/index.tsx
  src/router/protectedRoute.tsx
Labels: 우선순위: 🟡 중간, 우선순위: 🟠 높음, ♻️ Refactor, 🔥 Remove

#147 Feat/ Chatting 웹소켓 연결
  package.json
  src/api/chat/chatHelp/chatHelp.hooks.ts
  src/api/chat/chatHelp/chatHelpAPI.ts
  src/api/chat/chatHelp/chatHelpType.ts
  src/api/chat/chatHelpList/chatHelpListType.ts
  src/api/chat/chatList/chatListType.ts
  src/api/chat/chatMessages/chatMessagesAPI.ts
  src/api/chat/chatMessages/chatMessagesType.ts
  src/api/chat/chatWebSocket/chatWebSocket.hooks.ts
  src/api/chat/chatWebSocket/chatWebSocketAPI.ts
  src/api/chat/chatWebSocket/chatWebSocketType.ts
  src/api/chat/createChatRoom/createChatRoomType.ts
  src/api/chat/deleteChatRoom/deleteChatRoomType.ts
  src/api/myPage/myPage.hooks.ts
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatItem.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/bubbles/ChatMyBubble.tsx
  src/components/chat/bubbles/ChatOtherBubble.tsx
  src/components/common/Header.tsx
  src/hooks/getProfileImages.ts
  src/pages/chat/studentChatListPage.tsx
  src/pages/chat/studentChatRoomPage.tsx
  src/pages/chat/teacherChatListPage.tsx
  src/pages/chat/teacherChatRoomPage.tsx
  src/router/loggedRoutes.tsx
  src/types/chat.ts
  tailwind.config.js
  yarn.lock
Labels: 우선순위: 🟡 중간, 🎨 Design, ✨Feature, 🩹Chore, 💄style

#150 Fix/유저 프로필 버그 수정
  src/api/editProfile/editProfileAPI.ts
  src/components/navigatorBar/BaseNavBar.tsx
  src/hooks/login/useLogin.ts
  src/pages/editProfile/editProfile.tsx
  src/types/editProfileType.ts
Labels: 우선순위: 🟠 높음, ♻️ Refactor, 🎨 Design, 🐛Bug

#151 Fix/선생님 선택 모달 에러
  src/api/auth/findEmail/findEmail.hooks.ts
  src/api/auth/login/login.hooks.ts
  src/api/auth/resetPassword/resetPassword.hooks.ts
  src/api/auth/sendEmail/sendEmail.hooks.ts
  src/api/auth/signup/signup.hooks.ts
  src/api/myPage/myPage.hooks.ts
  src/api/social/social.hooks.ts
  src/context/AuthContextProvider.tsx
  src/context/UserInfoContextProvider.tsx
  src/hooks/findEmail/useFindEmail.ts
  src/hooks/login/useLogin.ts
  src/hooks/resetPassword/useResetPassword.ts
  src/hooks/signup/useSignupForm.ts
  src/hooks/useAuth.ts
  src/pages/auth/findEmailPage.tsx
  src/pages/auth/resetPasswordPage.tsx
  src/pages/auth/signupPage.tsx
  src/pages/main/homeFeedPage.tsx
  src/router/protectedRoute.tsx
  src/types/apiErrorType.ts
  src/types/myPageType.ts
Labels: 우선순위: 🟠 높음, ♻️ Refactor, 🐛Bug

#154 🚀 Deploy/배포 파일 작성
  .github/workflows/node.js.yml
  package.json
  src/assets/navBar/teacher/user_active.svg
  src/index.css
  src/pages/auth/findEmailPage.tsx
  src/pages/auth/resetPasswordPage.tsx
  src/pages/chat/studentChatListPage.tsx
  src/pages/chat/studentChatRoomPage.tsx
  src/pages/chat/teacherChatRoomPage.tsx
  src/router/protectedRoute.tsx
  vite.config.ts
  yarn.lock
Labels: 🚀 Deploy, 우선순위: 🟠 높음

#156 Refactor/무한 스크롤 응답 데이터 변경 반영
  src/api/homeFeed/homeFeed.hooks.ts
  src/api/postDetail/postDetail.hooks.ts
  src/pages/postDetail/postDetail.tsx
  src/types/postType.ts
Labels: 우선순위: 🟠 높음, ♻️ Refactor

#158 Chore/ Chatting 타입수정
  src/api/chat/chatHelp/chatHelp.hooks.ts
  src/api/chat/chatHelp/chatHelpAPI.ts
  src/api/chat/chatHelp/chatHelpType.ts
  src/api/chat/chatHelpList/chatHelpList.hooks.ts
  src/api/chat/chatHelpList/chatHelpListAPI.ts
  src/api/chat/chatHelpList/chatHelpListType.ts
  src/api/chat/chatList/chatList.hooks.ts
  src/api/chat/chatList/chatListAPI.ts
  src/api/chat/chatList/chatListType.ts
  src/api/chat/chatMessages/chatMessages.hooks.ts
  src/api/chat/chatMessages/chatMessagesAPI.ts
  src/api/chat/chatMessages/chatMessagesType.ts
  src/api/chat/chatWebSocket/chatWebSocket.hooks.ts
  src/api/chat/chatWebSocket/chatWebSocketAPI.ts
  src/api/chat/createChatRoom/createChatRoom.hooks.ts
  src/api/chat/createChatRoom/createChatRoomAPI.ts
  src/api/chat/createChatRoom/createChatRoomType.ts
  src/api/chat/deleteChatRoom/deleteChatRoom.hooks.ts
  src/api/chat/deleteChatRoom/deleteChatRoomAPI.ts
  src/api/chat/deleteChatRoom/deleteChatRoomType.ts
  src/components/chat/ChatMessage.tsx
  src/components/chat/HelpButton.tsx
  src/components/chat/bubbles/ChatMyBubble.tsx
  src/components/chat/bubbles/ChatOtherBubble.tsx
  src/components/chat/bubbles/ChatSystemBubble.tsx
  src/pages/chat/studentChatRoomPage.tsx
  src/pages/chat/teacherChatRoomPage.tsx
  src/pages/main/homeFeedPage.tsx
  src/types/chat.ts
Labels: 우선순위: 🟡 중간, ✨Feature, 🩹Chore, 💄style

#159 fix/학년 css 애니메이션 수정
  src/components/auth/GradeButton.tsx
  src/pages/main/homeFeedPage.tsx
Labels: 우선순위: 🟡 중간, 🎨 Design, 🐛Bug

#161 fix/애니메이션 에러 수정 및 보완
  src/components/comment/CommentModalSkeleton.tsx
  src/components/modal/CommentModal.tsx
  src/components/modal/TeacherListModal.tsx
  src/pages/auth/roleSelectPage.tsx
  src/router/index.tsx
Labels: 우선순위: 🟡 중간, 🎨 Design, 🐛Bug

#162 feat/게시글 삭제 기능
  src/api/deletePost/deletePost.hooks.ts
  src/api/deletePost/deletePostAPI.ts
  src/api/deletePost/deletePostType.ts
  src/components/main/FeedPost.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/hooks/deletePost/useDeletePost.ts
  src/pages/main/homeFeedPage.tsx
  src/pages/posting/createPostPage.tsx
Labels: 우선순위: 🟠 높음, ✨Feature

#163 Fix/ Mac 한글 조합 방지 추가
  src/api/chat/chatWebSocket/chatWebSocketAPI.ts
  src/components/chat/ChatInput.tsx
  src/pages/chat/studentChatRoomPage.tsx
  src/pages/chat/teacherChatRoomPage.tsx
  src/types/chat.ts
Labels: 🐛Bug, 🩹Chore

#165 style/채팅 리스트 스켈레톤 ui 추가
  src/components/chat/ChatListSkeleton.tsx
  src/pages/chat/studentChatListPage.tsx
Labels: 🎨 Design

#167 Fix/새로고침 시 /login 경로로 가는 에러
  src/api/axiosInstance.ts
  src/api/myPage/myPage.hooks.ts
  src/api/teacher/teacherQueries.ts
  src/components/main/FeedPostContent.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/context/AuthContextProvider.tsx
  src/hooks/login/useLogin.ts
  src/pages/chat/studentChatListPage.tsx
  src/pages/chat/teacherChatListPage.tsx
  src/pages/main/homeFeedPage.tsx
  src/pages/main/managedStudentListPage.tsx
Labels: 우선순위: 🔴 긴급, 🐛Bug

#170 Fix/댓글관련 에러 수정
  src/api/comment/fetchComment/fetchCommentType.ts
  src/api/comment/writeComment/writeCommentType.ts
  src/components/comment/CommentList.tsx
  src/components/comment/ReComment.tsx
  src/components/main/FeedPostButton.tsx
  src/components/main/FeedPostContent.tsx
  src/components/modal/CommentModal.tsx
  src/pages/main/homeFeedPage.tsx
Labels: 우선순위: 🟠 높음, 🐛Bug

#173 Feat/ 좋아요 기능 api연결
  src/api/homeFeed/heartBtn/heartBtnClick/heartCreate.hooks.ts
  src/api/homeFeed/heartBtn/heartBtnClick/heartCreateAPI.ts
  src/api/homeFeed/heartBtn/heartBtnClick/heartCreateType.ts
  src/api/homeFeed/heartBtn/heartBtnGet/fetchLikes.hooks.ts
  src/api/homeFeed/heartBtn/heartBtnGet/fetchLikesAPI.ts
  src/api/homeFeed/heartBtn/heartBtnGet/fetchLikesType.ts
  src/components/main/FeedPost.tsx
  src/components/main/FeedPostButton.tsx
  src/components/main/FeedPostContent.tsx
  src/components/modal/CommentModal.tsx
  src/pages/postDetail/postDetail.tsx
  src/stores/useCommentModalStore.ts
Labels: 우선순위: 🟠 높음, ♻️ Refactor, ✨Feature, 🩹Chore

#174 Feat/ Chat message details
  src/api/chat/chatMessages/chatMessages.hooks.ts
  src/api/chat/chatMessages/chatMessagesAPI.ts
  src/components/chat/bubbles/ChatMyBubble.tsx
  src/components/chat/bubbles/ChatOtherBubble.tsx
  src/components/modal/CreateChatModal.tsx
  src/components/modal/PreviewImageModal.tsx
  src/hooks/chat/useMergeMessages.ts
  src/hooks/useFileUpload.ts
  src/pages/chat/studentChatRoomPage.tsx
  src/pages/chat/teacherChatRoomPage.tsx
  src/types/chat.ts
  src/utils/getMessageMetadata.ts
Labels: 우선순위: 🟡 중간, ♻️ Refactor, 🎨 Design, ✨Feature

#175 Feat/게시글 수정
  package.json
  src/api/updatePost/updatePost.hooks.ts
  src/api/updatePost/updatePost.type.ts
  src/api/updatePost/updatePostAPI.ts
  src/components/main/FeedPostUserInfo.tsx
  src/hooks/updatePost/useUpdatePost.ts
  src/main.tsx
  src/pages/main/homeFeedPage.tsx
  src/pages/posting/createPostPage.tsx
  src/router/loggedRoutes.tsx
  yarn.lock
Labels: 우선순위: 🔴 긴급, ✨Feature

#176 Refactor/ ChatRoomPage 자동 스크롤 수정 및 리팩토링
  src/App.tsx
  src/api/auth/sendEmail/sendEmailAPI.ts
  src/api/axiosInstance.ts
  src/api/chat/chatHelp/chatHelpAPI.ts
  src/api/chat/chatHelpList/chatHelpListAPI.ts
  src/api/chat/chatList/chatListAPI.ts
  src/api/chat/chatMessages/chatMessagesAPI.ts
  src/api/chat/chatWebSocket/chatWebSocket.hooks.ts
  src/api/chat/chatWebSocket/chatWebSocketAPI.ts
  src/api/chat/createChatRoom/createChatRoomAPI.ts
  src/api/chat/deleteChatRoom/deleteChatRoomAPI.ts
  src/api/comment/writeComment/writeCommentAPI.ts
  src/api/createPosting/createPostingAPI.ts
  src/api/homeFeed/heartBtn/heartBtnGet/fetchLikesAPI.ts
  src/api/myPage/myPage.hooks.ts
  src/api/studentsList/studentsListAPI.ts
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatMessage.tsx
  src/components/comment/CommentList.tsx
  src/components/main/FeedPostButton.tsx
  src/components/main/FeedPostUserInfo.tsx
  src/components/modal/CancelMemberModal.tsx
  src/components/modal/CommentModal.tsx
  src/context/AuthContextProvider.tsx
  src/hooks/changeProfile/useEditAccountForm.ts
  src/hooks/changeProfile/useVerifyPasswordForm.ts
  src/hooks/chat/useMergeMessages.ts
  src/hooks/deletePost/useDeletePost.ts
  src/hooks/findEmail/useFindEmail.ts
  src/hooks/login/useLogin.ts
  src/hooks/logout/useLogout.ts
  src/hooks/resetPassword/useResetPassword.ts
  src/hooks/signup/useEmailVerification.ts
  src/hooks/signup/useSignupForm.ts
  src/hooks/teacherSelection/useTeacherSelection.ts
  src/hooks/useAuth.ts
  src/hooks/useFileUpload.ts
  src/pages/auth/loginHandlerPage.tsx
  src/pages/auth/signupCompletePage.tsx
  src/pages/auth/termsOfServicePage.tsx
  src/pages/chat/studentChatListPage.tsx
  src/pages/chat/studentChatRoomPage.tsx
  src/pages/chat/teacherChatRoomPage.tsx
  src/pages/editProfile/editProfile.tsx
  src/pages/main/managedStudentListPage.tsx
  src/pages/postDetail/postDetail.tsx
  src/pages/posting/createPostPage.tsx
  src/router/protectedRoute.tsx
  src/types/chat.ts
Labels: 우선순위: 🟢 낮음, ♻️ Refactor, 🐛Bug, 🩹Chore

#178 Chore/msw 주석 삭제
  src/main.tsx
Labels: 우선순위: 🟢 낮음, 💡Comment

#180 fix/ 선생님 목록 안불러오는 에러 수정
  src/components/modal/TeacherListModal.tsx
Labels: 🐛Bug

#181 Fix/이미지 오류일 때 기본 이미지 띄우기
  src/components/navigatorBar/BaseNavBar.tsx
Labels: 우선순위: 🔴 긴급, 🐛Bug

#183 Docs/리드미 작성
  README.md
  src/main.tsx
Labels: 📃 Docs

#184 Update README.md
  README.md
Labels: 🐛Bug
